### ISSUE TITLE
Cannot seem to decode live stream.

### ISSUE THREAD

**Issue by antithing** [elliotwoods/LTCSharp#1]
Hi, i know this is an old project, but I am attempting to read timecode from a lockit box, and decode it in realtime. I have your code building, but the exampleDecode project sticks at:

`if (FDecoder.GetQueueLength() > 0)  //Never gets past here.
                    {
                        try
                        {
                            var frame = FDecoder.Read();
                            var timecode = frame.getTimecode();
                            Console.WriteLine(timecode.ToString());
                        }
                        catch (Exception e)
                        {
                            Console.Write(e);
                        }
                    }`

It prints the device format, but there are no frames in the queue. Am I missing a step?

Thank you!

**Comment by antithing** [comment]
Ah, I had the input jack set to 'mic' instead of 'line-in'. Working great now. Thank you for the code!

**Comment by elliotwoods** [comment]
Glad to hear it works!
